const ApiPath = {
    GET_USER: '/api/users',
    PUT_USER: '/api/users/2',
    CREATE_USER: '/api/users',
    PATCH_USER: '/api/users/2',
    DELETE_USER: '/api/users/2',

    // AuthApiPath: {
    //     LOGIN_USER: '/api/v1/users/login',
    //     FORGET_PASSWORD_USER: '/api/v1/users/forgot/password',
    //     FORGET_PASSWORD_VERIFY: '/api/v1/users/forgot/password/verify/otp',
    //     RESET_PASSWORD: '/api/v1/users/reset/password',
    //     SIGNUP_USER: '/api/v1/users/create',
    //     OTP_USER: '/api/v1/users/verify-otp',
    //     CHANGE_PASSWORD: '/api/v1/users/change/password',
    //     OTP_VERIFY_USER: '/api/v1/users/resend-otp',
    //     SOCIAL_LOGIN_SIGNUP: '/api/v1/users/social/login-signup',
    //     LOGOUT_USER: '/api/v1/users/logout',
    //     STEP_USER: '/api/v1/company_information/add',
    //     SITE_ACCESS: '/api/v1/users/site_access',
    //     INDUSTRY_GROUPS: '/api/v1/industries',
    //     INDUSTRY_SUB_GROUPS: '/api/v1/industries/sub_industries/',
    //     BUSINESS_OWNERSHIP_TYPE: '/api/v1/business_ownership_type',
    //     COMPANY_LIST_TYPE: '/api/v1/company_information/get/all',
    //     EDIT_PROFILE : '/api/v1/user_profiles/',
    //     COMPANY_EDIT_PROFILE: '/api/v1/user_profiles/company/profile/',
    //     COMPANY_UPDATE_LOGO_BANNER: '/api/v1/user_profiles/company/logo/banner/',
    //     COMPANY_PROFILE_INFORMATION:'/api/v1/users/info',
    //     COMPANY_ADD_CERTIFICATES:'/api/v1/company_certificates/upload/',
    //     COMPANY_DELETE_CERTIFICATES:'/api/v1/company_certificates/',
    //     COMPANY_CERTIFICATES_LIST:'/api/v1/company_certificates/by/company/id/',
    //     MEMBERSHIP_GET_SESSION_ID: '/api/v1/payment/get/session/id',
    //     UPDATE_MEMBERSHIP_AMOUNT: '/api/v1/payment/update/session',
    //     UPDATE_SUBSCRIPTION_ID: '/api/v1/users/update/one/signal/details',
    //     SEARCH_COMPANY_USER: '/api/v1/users/search/all',
    //     UPDATE_USER_EXISTING_CERTIFICATIONS:'/api/v1/common/existing/certification/data',
    //     UPDATE_USER_TRADE_MEMBERSHIP:'/api/v1/common/membership/data',
    //     BUSINESS_GENESIS:"/api/v1/common/business/genesis",
    // },

    DashboardApiPath: {
        GET_ALL_POST: '/api/v1/post',
        GET_ALL_DASHBOARD_DATA: '/api/v1/dashboard/index',
        ADD_POST: '/api/v1/post/add',
        EDIT_POST:'/api/v1/post/update',
        LIKE_POST: '/api/v1/post/like',
        POST_LIKE_USER_LIST : '/api/v1/post/like/list',
        COMMENT_POST: '/api/v1/post/comment',
        ATTACHMENT_UPLOAD: '/api/v1/user_photos/upload',
        POST_ALL_COMMENT_LIST: 'api/v1/post/get_comments',
        NESTED_COMMENT_LIST:'api/v1/post/nested_comments',
        LIKE_COMMENT: '/api/v1/comment_like',
        DASHBOARD_POST_OPPORTUNITY: '/api/v1/post_opportunity/my',
        POST_FEATURE: 'api/v1/post/feature',
        PENDING_ENDORSEMENT: 'api/v1/endorsement/endorsement-list-to-approve',
        UPDATE_STATUS_ENDORSEMENT: '/api/v1/endorsement/update-status',
        ALL_USER_WITH_SEARCH: `/api/v1/users/all`,
        USER_UPDATE_PROFILE_STATUS: '/api/v1/users/update/status',
        GET_SINGLE_POST:'/api/v1/post/by_id'
    },

}

export default ApiPath;
